//! verify.html renderer.
//!
//! Ships a static HTML page (no JS, no WASM, no CSS framework, no external
//! resources) that displays the *facts* a published dataset's sealed record
//! asserts — a corpus summary, the Sigstore signing-identity policy, and the
//! bundle's self-asserted file paths — plus a pre-filled stock `cosign
//! verify-blob-attestation --new-bundle-format` command. Visitors verify the
//! bundle without Attestrum installed (CLAUDE.md §12 vendor neutrality).
//!
//! **The page performs no cryptographic check of its own and renders no
//! affirmative "verified" verdict.** The verdict belongs to `cosign`, run on
//! the visitor's machine. A non-cryptographic page that looked verified would
//! be a false trust signal — the worst failure class for a provenance
//! product — so the page hands off to `cosign` and judges nothing itself.
//! See `docs/diagrams/sprint-6/verify-page.md` for the contract.
//!
//! Determinism: pure `String::replace` substitution; integer corpus counts
//! formatted without locale separators; no wall-clock; no map iteration.
//! Output is byte-identical across the 4-target CI matrix as long as the
//! input plan fields are byte-identical (they come from sorted-key sources
//! upstream — CLI flags + `attestrum_attest::extract_identity()` +
//! `read_manifest_stats()`).
//!
//! HTML escaping: hand-rolled per CLAUDE.md §14 (no `html_escape` dep —
//! single-purpose helper). Covers the five OWASP-recommended HTML-context
//! characters: `& < > " '`. The two corpus-count fields are `u64`, formatted
//! to ASCII digits, and need no escaping, but pass through the template
//! uniformly.

use crate::{AttestrumEmitError, VerifyHtmlPlan};
use attestrum_attest::TRAINING_CORPUS_PREDICATE_TYPE;

const HTML_TEMPLATE: &str = r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Verify — {dataset}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2em auto; padding: 0 1em; color: #222; }
  h1 { font-size: 1.4em; }
  code, pre { background: #f4f4f4; padding: 0.2em 0.4em; border-radius: 3px; }
  pre { padding: 1em; overflow-x: auto; white-space: pre-wrap; word-break: break-all; }
  .facts { border-left: 3px solid #555; padding-left: 1em; margin: 1em 0; }
  .facts dt { font-weight: bold; margin-top: 0.5em; }
  .notice { border: 2px dashed #b58900; background: #fdf6e3; padding: 0.8em 1em; margin: 1.5em 0; border-radius: 4px; }
  .notice strong { color: #905c00; }
  footer { margin-top: 2em; font-size: 0.85em; color: #666; }
</style>
</head>
<body>
<h1>{dataset}</h1>
<p>This dataset was published with Attestrum. The page below shows what the
dataset's sealed record <em>asserts</em> — its corpus summary, the signing
identity, and the file paths it points to — and gives you the command to
check it yourself.</p>

<div class="notice">
<strong>This page does not verify anything.</strong> It only displays the
values recorded in the bundle. To actually confirm the signature, run the
<code>cosign</code> command below on your own machine — that is what
produces a real cryptographic result.
</div>

<h2>Corpus summary</h2>
<p>Self-asserted by the sealed manifest (confirm by running the command below):</p>
<dl class="facts">
  <dt>Documents</dt>
  <dd>{doc_count}</dd>
  <dt>Total bytes</dt>
  <dd>{total_bytes}</dd>
</dl>

<h2>Signing identity</h2>
<dl class="facts">
  <dt>Certificate identity (SAN)</dt>
  <dd><code>{san}</code></dd>
  <dt>OIDC issuer</dt>
  <dd><code>{issuer}</code></dd>
</dl>

<h2>Bundle files</h2>
<dl class="facts">
  <dt>Sigstore bundle</dt>
  <dd><code>{bundle_path}</code></dd>
  <dt>Sealed manifest</dt>
  <dd><code>{manifest_path}</code></dd>
</dl>

<h2>Verify it yourself</h2>
<p>Run this with stock Sigstore tooling — no Attestrum install required.
<code>cosign</code> contacts the Sigstore network (TUF, Rekor) to check the
certificate chain and transparency-log inclusion, then prints the result:</p>
<pre>cosign verify-blob-attestation \
  --new-bundle-format \
  --type {predicate_type} \
  --bundle {bundle_path} \
  --certificate-identity {san} \
  --certificate-oidc-issuer {issuer} \
  {manifest_path}</pre>

<p>The Attestrum CLI's <code>attestrum verify</code> runs the same Sigstore
verification from the command line. See
<a href="https://github.com/Attestrum/Attestrum">github.com/Attestrum/Attestrum</a>.</p>

<footer>Generated by Attestrum. The cryptographic result comes from
<code>cosign</code>, not from this page.</footer>
</body>
</html>
"#;

/// Render the static verify.html stub. See module docs for the determinism
/// contract and the vendor-neutral CLI-command rationale.
pub fn render(plan: &VerifyHtmlPlan) -> Result<String, AttestrumEmitError> {
    if plan.dataset_name.is_empty() {
        return Err(AttestrumEmitError::VerifyHtml(
            "dataset_name is required".to_string(),
        ));
    }
    if plan.certificate_identity.is_empty() {
        return Err(AttestrumEmitError::VerifyHtml(
            "certificate_identity is required".to_string(),
        ));
    }
    if plan.certificate_oidc_issuer.is_empty() {
        return Err(AttestrumEmitError::VerifyHtml(
            "certificate_oidc_issuer is required".to_string(),
        ));
    }
    if plan.bundle_path_in_repo.is_empty() {
        return Err(AttestrumEmitError::VerifyHtml(
            "bundle_path_in_repo is required".to_string(),
        ));
    }
    if plan.manifest_path_in_repo.is_empty() {
        return Err(AttestrumEmitError::VerifyHtml(
            "manifest_path_in_repo is required".to_string(),
        ));
    }

    let dataset = html_escape(&plan.dataset_name);
    let san = html_escape(&plan.certificate_identity);
    let issuer = html_escape(&plan.certificate_oidc_issuer);
    let bundle_path = html_escape(&plan.bundle_path_in_repo);
    let manifest_path = html_escape(&plan.manifest_path_in_repo);
    // Corpus counts are `u64`; their decimal formatting is ASCII digits
    // only (no locale separators — that would be non-deterministic across
    // the CI matrix), so no escaping is required.
    let doc_count = plan.manifest_stats.leaf_count.to_string();
    let total_bytes = plan.manifest_stats.total_bytes.to_string();
    // Predicate-type URI is a fixed const (PROTECTED `attestrum-attest`); no
    // attacker-controlled input. Escape anyway for templating uniformity.
    let predicate_type = html_escape(TRAINING_CORPUS_PREDICATE_TYPE);

    // Sequential `.replace` instead of `format!` keeps the template literal
    // readable + avoids `format!`-arg-order surprises. The replace order
    // matters only if a substituted value contains another placeholder
    // verbatim — html_escape would escape any `{` / `}` since they're not
    // in the escape set, but the template placeholders are all
    // alphanumeric + underscore so no collision is possible.
    let out = HTML_TEMPLATE
        .replace("{dataset}", &dataset)
        .replace("{san}", &san)
        .replace("{issuer}", &issuer)
        .replace("{bundle_path}", &bundle_path)
        .replace("{manifest_path}", &manifest_path)
        .replace("{doc_count}", &doc_count)
        .replace("{total_bytes}", &total_bytes)
        .replace("{predicate_type}", &predicate_type);

    Ok(out)
}

/// Escape the five OWASP-recommended HTML-context characters. Non-ASCII
/// characters pass through as valid UTF-8 (browsers render them fine in
/// HTML5 `<meta charset="utf-8">` context).
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#x27;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_plan() -> VerifyHtmlPlan {
        VerifyHtmlPlan {
            dataset_name: "my-org/my-dataset".to_string(),
            certificate_identity:
                "https://github.com/my-org/my-dataset/.github/workflows/build.yml@refs/heads/main"
                    .to_string(),
            certificate_oidc_issuer: "https://token.actions.githubusercontent.com".to_string(),
            bundle_path_in_repo: "attestrum/bundle.sigstore.json".to_string(),
            manifest_path_in_repo: "attestrum/manifest.parquet".to_string(),
            manifest_stats: crate::ManifestStats {
                leaf_count: 1234,
                total_bytes: 5_678_900,
            },
        }
    }

    #[test]
    fn render_contains_dataset_name_and_identity_and_cosign_command() {
        let html = render(&fixture_plan()).expect("render");
        assert!(html.contains("my-org/my-dataset"));
        assert!(html.contains(
            "https://github.com/my-org/my-dataset/.github/workflows/build.yml@refs/heads/main"
        ));
        assert!(html.contains("https://token.actions.githubusercontent.com"));
        assert!(html.contains("cosign verify-blob-attestation"));
        assert!(html.contains("--new-bundle-format"));
        assert!(html.contains("attestrum/bundle.sigstore.json"));
        assert!(html.contains("attestrum/manifest.parquet"));
    }

    #[test]
    fn render_shows_corpus_summary_counts() {
        let html = render(&fixture_plan()).expect("render");
        // The doc count and byte count are rendered as plain decimal
        // integers (no locale separators — determinism).
        assert!(html.contains("1234"), "doc count missing: {html}");
        assert!(html.contains("5678900"), "byte count missing: {html}");
        assert!(html.contains("Corpus summary"));
    }

    #[test]
    fn render_has_no_affirmative_verdict() {
        // The grade-wall constraint: a non-cryptographic page must never
        // present itself as a completed verification. No affirmative
        // verdict words anywhere in the output.
        let html = render(&fixture_plan()).expect("render").to_lowercase();
        for forbidden in [
            "verified",
            "✓",
            "checks passed",
            "check passed",
            "verification successful",
            "signature valid",
        ] {
            assert!(
                !html.contains(forbidden),
                "page must render no affirmative verdict, found {forbidden:?}"
            );
        }
    }

    #[test]
    fn render_carries_does_not_verify_notice() {
        let html = render(&fixture_plan()).expect("render");
        assert!(
            html.contains("This page does not verify anything"),
            "explicit does-not-verify notice missing"
        );
    }

    #[test]
    fn render_makes_no_offline_or_merkle_recompute_claim() {
        // Honesty constraints: cosign needs the network (not offline), and
        // no tool reachable from this page recomputes the Merkle root.
        let html = render(&fixture_plan()).expect("render").to_lowercase();
        assert!(!html.contains("offline"), "must not claim offline: {html}");
        assert!(
            !html.contains("merkle"),
            "must not display/claim a Merkle root: {html}"
        );
        assert!(
            !html.contains("wasm"),
            "must not promise a wasm verifier: {html}"
        );
    }

    #[test]
    fn render_escapes_html_injection_in_san() {
        let mut plan = fixture_plan();
        plan.certificate_identity = "<script>alert('xss')</script>".to_string();
        let html = render(&plan).expect("render");
        assert!(
            !html.contains("<script>alert('xss')</script>"),
            "raw injection must not appear: {html}"
        );
        assert!(
            html.contains("&lt;script&gt;alert(&#x27;xss&#x27;)&lt;/script&gt;"),
            "escaped form must appear: {html}"
        );
    }

    #[test]
    fn render_escapes_ampersand_and_quotes_in_oidc_issuer() {
        let mut plan = fixture_plan();
        plan.certificate_oidc_issuer = r#"https://x.example?a=b&c="d""#.to_string();
        let html = render(&plan).expect("render");
        assert!(html.contains("a=b&amp;c=&quot;d&quot;"), "got: {html}");
    }

    #[test]
    fn render_is_deterministic_across_calls() {
        let a = render(&fixture_plan()).expect("render a");
        let b = render(&fixture_plan()).expect("render b");
        assert_eq!(a, b);
    }

    #[test]
    fn render_rejects_empty_dataset_name() {
        let mut plan = fixture_plan();
        plan.dataset_name = String::new();
        let err = render(&plan).expect_err("empty dataset_name must error");
        assert!(matches!(err, AttestrumEmitError::VerifyHtml(_)));
    }

    #[test]
    fn render_rejects_empty_certificate_identity() {
        let mut plan = fixture_plan();
        plan.certificate_identity = String::new();
        let err = render(&plan).expect_err("empty certificate_identity must error");
        assert!(matches!(err, AttestrumEmitError::VerifyHtml(_)));
    }

    #[test]
    fn render_rejects_empty_certificate_oidc_issuer() {
        let mut plan = fixture_plan();
        plan.certificate_oidc_issuer = String::new();
        let err = render(&plan).expect_err("empty certificate_oidc_issuer must error");
        assert!(matches!(err, AttestrumEmitError::VerifyHtml(_)));
    }

    #[test]
    fn render_rejects_empty_bundle_path() {
        let mut plan = fixture_plan();
        plan.bundle_path_in_repo = String::new();
        let err = render(&plan).expect_err("empty bundle_path_in_repo must error");
        assert!(matches!(err, AttestrumEmitError::VerifyHtml(_)));
    }

    #[test]
    fn render_rejects_empty_manifest_path() {
        let mut plan = fixture_plan();
        plan.manifest_path_in_repo = String::new();
        let err = render(&plan).expect_err("empty manifest_path_in_repo must error");
        assert!(matches!(err, AttestrumEmitError::VerifyHtml(_)));
    }

    #[test]
    fn html_escape_covers_five_owasp_characters() {
        assert_eq!(html_escape("a&b"), "a&amp;b");
        assert_eq!(html_escape("a<b"), "a&lt;b");
        assert_eq!(html_escape("a>b"), "a&gt;b");
        assert_eq!(html_escape("a\"b"), "a&quot;b");
        assert_eq!(html_escape("a'b"), "a&#x27;b");
    }

    #[test]
    fn html_escape_passes_non_ascii_through() {
        // UTF-8 chars are rendered fine in HTML5 with <meta charset="utf-8">.
        assert_eq!(html_escape("café—λ"), "café—λ");
    }
}
