//! Golden-vector test for `attestrum_merkle::merkle_root` against the
//! RFC 6962 + BLAKE3 vectors generated by
//! `tests/fixtures/rfc6962/generate.py`. The Python generator is the
//! independent oracle; this test fails if the Rust implementation
//! disagrees on any case.

use attestrum_core::hex;
use attestrum_merkle::{audit_path, merkle_root, verify_audit_path, MerkleTree};
use serde::Deserialize;

#[derive(Deserialize)]
struct VectorFile {
    cases: Vec<VectorCase>,
}

#[derive(Deserialize)]
struct VectorCase {
    name: String,
    leaves_hex: Vec<String>,
    expected_root_hex: String,
    #[serde(default)]
    audit_paths: Vec<AuditPathCase>,
}

#[derive(Deserialize)]
struct AuditPathCase {
    leaf_index: usize,
    expected_path_hex: Vec<String>,
}

fn decode_32(h: &str, label: &str) -> [u8; 32] {
    let bytes = hex::decode(h).unwrap_or_else(|e| panic!("{label}: hex decode failed: {e}"));
    assert_eq!(
        bytes.len(),
        32,
        "{label}: must be 32 bytes, got {}",
        bytes.len()
    );
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    arr
}

#[test]
fn rfc6962_blake3_golden_vectors() {
    let raw = include_str!("fixtures/rfc6962/vectors.json");
    let parsed: VectorFile = serde_json::from_str(raw).expect("parse vectors.json");
    assert!(
        !parsed.cases.is_empty(),
        "vectors.json contains no cases — generator output is empty?"
    );

    for case in &parsed.cases {
        let leaves: Vec<[u8; 32]> = case
            .leaves_hex
            .iter()
            .map(|h| decode_32(h, &format!("case `{}` leaf", case.name)))
            .collect();

        // 1. Root matches the independent Python BLAKE3 oracle.
        let computed_root = merkle_root(&leaves);
        let computed_root_hex = hex::encode_32(&computed_root);
        assert_eq!(
            computed_root_hex, case.expected_root_hex,
            "RFC 6962 + BLAKE3 root mismatch for case `{}`:\n  computed: {}\n  expected: {}",
            case.name, computed_root_hex, case.expected_root_hex
        );

        // 2. Audit paths match the oracle for every recorded leaf
        //    index, and each one roundtrips through verify_audit_path.
        let tree = MerkleTree::new(leaves.clone());
        for ap in &case.audit_paths {
            let label = format!("case `{}` audit_path[{}]", case.name, ap.leaf_index);
            let expected_path: Vec<[u8; 32]> = ap
                .expected_path_hex
                .iter()
                .map(|h| decode_32(h, &format!("{label} sibling")))
                .collect();
            let computed_path = audit_path(&tree, ap.leaf_index)
                .unwrap_or_else(|e| panic!("{label}: audit_path failed: {e}"));
            assert_eq!(
                computed_path, expected_path,
                "{label}: path bytes diverge from independent Python oracle\n  computed: {:?}\n  expected: {:?}",
                computed_path.iter().map(hex::encode_32).collect::<Vec<_>>(),
                expected_path.iter().map(hex::encode_32).collect::<Vec<_>>(),
            );
            assert!(
                verify_audit_path(
                    &computed_root,
                    &leaves[ap.leaf_index],
                    ap.leaf_index,
                    leaves.len(),
                    &computed_path,
                ),
                "{label}: verify_audit_path rejected a path that audit_path just produced",
            );
        }
    }
}
