[package]
name = "attestrum-compose"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
attestrum-core     = { path = "../attestrum-core",     version = "0.0.1" }
attestrum-manifest = { path = "../attestrum-manifest", version = "0.1.0" }
attestrum-merkle   = { path = "../attestrum-merkle",   version = "0.1.0" }
attestrum-attest   = { path = "../attestrum-attest",   version = "0.0.1" }
serde              = { workspace = true }
serde_json         = { workspace = true }
