//! Tracked generator for `tests/golden/minhash-vectors.txt`.
//!
//! The golden file is the byte-identity anchor shared by two gates: the native
//! cross-check test (`tests/crosscheck.rs`) and the wasm cross-check CI gate
//! (`tools/wasm-crosscheck/run.mjs`). Both recompute each passage's MinHash and
//! assert it equals the committed hex — the native side proves the kernel still
//! matches, the wasm side proves the actual `.wasm` matches. This generator is
//! the single source of the passage list; regenerate after intentionally
//! changing it:
//!
//! ```text
//! cargo run -p attestrum-fingerprint-wasm --example gen_golden \
//!   > crates/attestrum-fingerprint-wasm/tests/golden/minhash-vectors.txt
//! ```
//!
//! Line format (skip blank lines and `#` comments): `label\tinput\thex,..x128`.
//! The 128 hex values are the lowercase zero-padded little-endian `u64`
//! permutations, comma-joined. Passages are single-line by construction (no tab
//! or newline in any input).

use attestrum_text_minhash::{minhash, normalize_text};

/// (label, input) passages. Curated to exercise the kernel's branches plus a
/// realistic near-match passage shape:
/// - empty (→ all `u64::MAX`),
/// - sub-5-token fallback (single whole-token-list shingle),
/// - exactly-5 tokens (single overlapping window),
/// - Unicode (NFC + Unicode-aware lowercase),
/// - a long multi-shingle passage and a one-word paraphrase of it.
const PASSAGES: &[(&str, &str)] = &[
    ("empty", ""),
    ("short-two", "hello world"),
    ("exact-five", "the quick brown fox jumps"),
    ("unicode-cafe", "Café CRÈME — Ünïcödé NFC Tëst Passage"),
    (
        "long-passage",
        "the quick brown fox jumps over the lazy dog in the sunny meadow at noon during the warm summer afternoon while the birds sing happily in the tall green trees",
    ),
    (
        "long-paraphrase",
        "the quick brown fox jumped over the lazy dog in the sunny meadow at noon during the warm summer afternoon while the birds sing happily in the tall green trees",
    ),
];

fn main() {
    println!("# attestrum-fingerprint-wasm golden MinHash vectors");
    println!("# GENERATED by `cargo run -p attestrum-fingerprint-wasm --example gen_golden`.");
    println!("# Format: label<TAB>input<TAB>128 comma-joined lowercase hex little-endian u64.");
    println!("# The byte-identity anchor for tests/crosscheck.rs + tools/wasm-crosscheck/run.mjs.");
    for (label, input) in PASSAGES {
        let sig = minhash::compute(&normalize_text(input));
        let hex: Vec<String> = sig.iter().map(|v| format!("{v:016x}")).collect();
        println!("{label}\t{input}\t{}", hex.join(","));
    }
}
